### ISSUE TITLE
Undefined "method" key while serializing certain exceptions: real exception swallowed

### ISSUE THREAD

**Issue by weaverryan** [netgen-layouts/layouts-core#27] opened 2022-08-24 19:46 UTC
Hi!

While editing a layout, I got this nasty error in an Ajax call:

<img width="1174" alt="Screen Shot 2022-08-24 at 3 40 19 PM" src="https://user-images.githubusercontent.com/121003/186508312-805a804d-696d-4281-afb2-c2572ae8a0bd.png">

What *actually* happened is that I made a mistake. The page *should* be showing me this error:

<img width="1188" alt="Screen Shot 2022-08-24 at 3 41 06 PM" src="https://user-images.githubusercontent.com/121003/186508448-69cba434-6e59-4f8f-8c05-a920b7ea5ffb.png">

That's from a mistake in my code. However, it's hidden because `ExceptionSerializerListener` fails when serializing the exception on this line: https://github.com/netgen-layouts/layouts-core/blob/master/bundles/LayoutsAdminBundle/EventListener/ExceptionSerializerListener.php#L73

The full stack trace is:

<img width="942" alt="Screen Shot 2022-08-24 at 3 42 49 PM" src="https://user-images.githubusercontent.com/121003/186508796-2dd082cc-3249-45cb-94e5-382db53833b1.png">

For some reason, when the exception is being serialized, the serialized tries to call `getMethod()` on `RequestDataCollector`...  `$this->data` is an empty array at that point, so things explode.

You should be able to repeat the error via this branch - https://github.com/weaverryan/layouts-symfony-barebones/tree/swallowed-error - then create/edit a layout.

Cheers!

**Comment by emodric** [comment] 2022-08-25 11:28
Hm, this works fine for me i.e. the original exception is shown, and not the `Undefined array key` one.

![image](https://user-images.githubusercontent.com/362286/186652639-525b35eb-8d58-4b94-989d-8dcaf18876ca.png)

**Comment by weaverryan** [comment] 2022-09-07 19:11
I have a new repo to try this on. AND, I think I know why you didn't see the same bad behavior as me. It is all explained in this README: https://github.com/weaverryan/netgens-layouts-playing/tree/exception_swallow

But, in short, when you "trigger" the error (which is from a bug in my code), the layouts admin page breaks (of course) and TWO Ajax requests fail in the background. One of these DOES show the correct error as JSON. The OTHER failed request shows the "bad" undefined array key error from my screenshot.

Cheers!

**Comment by emodric** [comment] 2022-09-08 08:05
@weaverryan I still can't reproduce! I indeed get two errors the first time around, but both of them are "normal"

![image](https://user-images.githubusercontent.com/362286/189069196-09950edc-ffd6-4c7c-be69-ccbfccf93011.png)
![image](https://user-images.githubusercontent.com/362286/189069230-6d558523-ef8f-4184-a0c3-f86eb12b50f1.png)

Can you share some more details on your environment and optionally `composer.lock` file? Maybe the "bad" error is due to some combination of dependencies.

**Comment by weaverryan** [comment] 2022-09-08 13:57
Ah, that's crazy! Well, if you still can't replicate it, then I don't think we'll be able to fix it - I can't think of what system differences would cause this (I don't have Xdebug installed... I'm not sure if that could be a difference).

**Comment by emodric** [comment] 2022-09-08 13:58
Can you just pack the entire project + DB and send it to me, so I can test that way.

**Comment by weaverryan** [comment] 2022-09-09 12:55
As we discussed, that's what the above is - that's the exact code, and even the exact database due to the migrations and fixtures. So, I think it must be triggered by some difference in our php installs/versions? I wouldn't worry about it, until someone else hits the same issue.

**Comment by emodric** [comment] 2022-09-09 13:33
Allright!

I'll close this then, feel free to reopen if you have a different reproducer :)

**Closed** 2022-09-09 13:33 UTC
